// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stango.Server.Data.Contexts;

#nullable disable

namespace Stango.Server.Migrations
{
    [DbContext(typeof(DeveloperDbContext))]
    partial class DeveloperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Stango.Shared.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3f88f7f-4ae2-4453-9593-45573b9b5644"),
                            Company = "Microsoft",
                            Email = "codefather@code.com",
                            UserName = "CodeFather"
                        },
                        new
                        {
                            Id = new Guid("5bf28ecc-382b-4313-b768-ebe98e171fe6"),
                            Company = "CodeUnparalled",
                            Email = "chiefscientist@code.com",
                            UserName = "ChiefScientist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
